version: '3.6'
services:
    node:
        image: node:11
        command: './node_modules/.bin/nodemon src/index.js'
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - '4000:4000'